name = "advaitswaroopservices"
compatibility_date = "2024-12-19"

[build]
command = "pnpm run build"

[assets]
directory = "./dist"

[vars]
NODE_ENV = "production"
SITE_URL = "https://www.advaitswaroopservices.com"
GTM_ID = "GTM-M4TWQ6FF"
ANALYTICS_ID = "G-YW0VGF6P2D"
